services:
  redis:
    image: 'redis:latest'
    ports:
      - '6379:6379'
    container_name: 'inzynierka-redis'
    restart: always

  db:
    image: postgres:latest
    platform: linux/arm64
    container_name: inzynierka-postgres
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=inzynierka
      - POSTGRES_DB=inzynierka_db
    volumes:
      - postgres_data:/var/lib/postgresql

volumes:
  postgres_data:
